---

- hosts: 192.168.56.205
  tasks:
  - name: Create multiple files
    file: 
      path: "/tmp/{{ item }}"
      state: touch
    with_items:
    - test01.txt
    - test02.txt
    - test03.txt
    - test04.txt
